server:
  port: 1919

spring:
  application:
    name: API-GATWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: AUTH
              uri: http://localhost:9001
              predicates:
                - Path=/auth/**
            
            - id: TASK
              uri: http://localhost:9002
              predicates:
                - Path=/tasks/**
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
